package com.vo;

import java.io.Serializable;


public class ProductParamVO implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column product_param.id
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column product_param.product_id
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column product_param.display_name
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column product_param.param_id
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    private Long paramId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column product_param.param_value
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    private String paramValue;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column product_param.param_type
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    private String paramType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column product_param.create_time
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column product_param.update_time
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    private Long updateTime;

    private int orderId;


    public int getOrderId() {
        return orderId;
    }


    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }


    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column product_param.id
     *
     * @return the value of product_param.id
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    public Long getId() {
        return id;
    }


    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column product_param.id
     *
     * @param id
     *            the value for product_param.id
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }


    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column product_param.product_id
     *
     * @return the value of product_param.product_id
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    public Long getProductId() {
        return productId;
    }


    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column product_param.product_id
     *
     * @param productId
     *            the value for product_param.product_id
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }


    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column product_param.display_name
     *
     * @return the value of product_param.display_name
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    public String getDisplayName() {
        return displayName;
    }


    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column product_param.display_name
     *
     * @param displayName
     *            the value for product_param.display_name
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }


    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column product_param.param_id
     *
     * @return the value of product_param.param_id
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    public Long getParamId() {
        return paramId;
    }


    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column product_param.param_id
     *
     * @param paramId
     *            the value for product_param.param_id
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    public void setParamId(Long paramId) {
        this.paramId = paramId;
    }


    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column product_param.param_value
     *
     * @return the value of product_param.param_value
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    public String getParamValue() {
        return paramValue;
    }


    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column product_param.param_value
     *
     * @param paramValue
     *            the value for product_param.param_value
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue == null ? null : paramValue.trim();
    }


    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column product_param.param_type
     *
     * @return the value of product_param.param_type
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    public String getParamType() {
        return paramType;
    }


    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column product_param.param_type
     *
     * @param paramType
     *            the value for product_param.param_type
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    public void setParamType(String paramType) {
        this.paramType = paramType;
    }


    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column product_param.create_time
     *
     * @return the value of product_param.create_time
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    public Long getCreateTime() {
        return createTime;
    }


    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column product_param.create_time
     *
     * @param createTime
     *            the value for product_param.create_time
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }


    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column product_param.update_time
     *
     * @return the value of product_param.update_time
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    public Long getUpdateTime() {
        return updateTime;
    }


    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column product_param.update_time
     *
     * @param updateTime
     *            the value for product_param.update_time
     *
     * @mbggenerated Wed Feb 04 16:29:28 CST 2015
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}