package com.vo;

public class TaobaoPicInfoVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_pic_info.id
     *
     * @mbggenerated Mon Jul 25 11:38:22 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_pic_info.taobao_url
     *
     * @mbggenerated Mon Jul 25 11:38:22 CST 2016
     */
    private String taobaoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_pic_info.yam_url
     *
     * @mbggenerated Mon Jul 25 11:38:22 CST 2016
     */
    private String yamUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_pic_info.create_time
     *
     * @mbggenerated Mon Jul 25 11:38:22 CST 2016
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_pic_info.update_time
     *
     * @mbggenerated Mon Jul 25 11:38:22 CST 2016
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_pic_info.id
     *
     * @return the value of taobao_pic_info.id
     *
     * @mbggenerated Mon Jul 25 11:38:22 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_pic_info.id
     *
     * @param id the value for taobao_pic_info.id
     *
     * @mbggenerated Mon Jul 25 11:38:22 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_pic_info.taobao_url
     *
     * @return the value of taobao_pic_info.taobao_url
     *
     * @mbggenerated Mon Jul 25 11:38:22 CST 2016
     */
    public String getTaobaoUrl() {
        return taobaoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_pic_info.taobao_url
     *
     * @param taobaoUrl the value for taobao_pic_info.taobao_url
     *
     * @mbggenerated Mon Jul 25 11:38:22 CST 2016
     */
    public void setTaobaoUrl(String taobaoUrl) {
        this.taobaoUrl = taobaoUrl == null ? null : taobaoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_pic_info.yam_url
     *
     * @return the value of taobao_pic_info.yam_url
     *
     * @mbggenerated Mon Jul 25 11:38:22 CST 2016
     */
    public String getYamUrl() {
        return yamUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_pic_info.yam_url
     *
     * @param yamUrl the value for taobao_pic_info.yam_url
     *
     * @mbggenerated Mon Jul 25 11:38:22 CST 2016
     */
    public void setYamUrl(String yamUrl) {
        this.yamUrl = yamUrl == null ? null : yamUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_pic_info.create_time
     *
     * @return the value of taobao_pic_info.create_time
     *
     * @mbggenerated Mon Jul 25 11:38:22 CST 2016
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_pic_info.create_time
     *
     * @param createTime the value for taobao_pic_info.create_time
     *
     * @mbggenerated Mon Jul 25 11:38:22 CST 2016
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_pic_info.update_time
     *
     * @return the value of taobao_pic_info.update_time
     *
     * @mbggenerated Mon Jul 25 11:38:22 CST 2016
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_pic_info.update_time
     *
     * @param updateTime the value for taobao_pic_info.update_time
     *
     * @mbggenerated Mon Jul 25 11:38:22 CST 2016
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}